---

- name: Install dependencies through APT
  become: true
  apt:
    name: inotify-tools
    state: latest
    update_cache: true

- name: Install Hex and Rebar
  become: true
  become_user: "{{ phoenix_user }}"
  command: "mix {{ item.name }} --force"
  args:
    creates: "~/.mix/{{ item.file }}"
  with_items:
    - { name: "local.hex",   file: "archives/hex.ez" }
    - { name: "local.rebar", file: "rebar" }

- name: Install dependencies through Hex
  become: true
  become_user: "{{ phoenix_user }}"
  command: mix deps.get
  environment:
    MIX_ENV: "{{ phoenix_env }}"
  args:
    chdir: "{{ phoenix_path }}"
  notify: restart phoenix
