---

- name: Stop Phoenix if it exists for editing the user
  become: true
  service:
    name: phoenix
    state: stopped
  ignore_errors: true

- name: Ensure app user group exists
  become: true
  group:
    state: present
    name:  "{{ phoenix_group }}"
  notify: restart phoenix

- name: Ensure app user exists
  become: true
  user:
    state:  present
    name:   "{{ phoenix_user }}"
    group:  "{{ phoenix_group }}"
    system: "{{ phoenix_system_user }}"
    home:   "{{ phoenix_system_user | ternary(phoenix_path, '/home/' ~ phoenix_user) }}"
  notify: restart phoenix

- name: Create app directory with correct permissions
  become: true
  file:
    state:   directory
    path:    "{{ phoenix_path }}"
    owner:   "{{ phoenix_user }}"
    group:   "{{ phoenix_group }}"
    recurse: true
  notify: restart phoenix
